options:
  logging: CLOUD_LOGGING_ONLY


steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/community-incident-app/community-backend:$SHORT_SHA',
        './server'
      ]

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/community-incident-app/community-backend:$SHORT_SHA'
      ]

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'community-backend',
        '--image',
        'gcr.io/community-incident-app/community-backend:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'MONGO_URI=mongodb+srv://syedamaseeratabassum:Maseera%4029@cluster0.mongodb.net/COMMUNITY-INCIDENT-APP?retryWrites=true&w=majority,JWT_SECRET=your_jwt_secret,ADMIN_SETUP_SECRET=mySuperSecretCode123!',
        '--port',
        '5000'
      ]

  
    # Build frontend with backend API URL
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     [
  #       'build',
  #       # '--build-arg',
  #       # 'REACT_APP_API_URL=https://https://community-backend-402506450695.us-central1.run.app',
  #       '-t',
  #       'gcr.io/community-incident-app/community-frontend:$SHORT_SHA',
  #       './client'
  #     ]
      # Build frontend with backend API URL
    - name: 'gcr.io/cloud-builders/docker'
      args:
        [
          'build',
          '-t',
          'gcr.io/community-incident-app/community-frontend:$SHORT_SHA',
          '--build-arg',
          'REACT_APP_API_URL=https://community-backend-402506450695.us-central1.run.app/api/',
          './client'
        ]

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/community-incident-app/community-frontend:$SHORT_SHA'
      ]

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'community-frontend',
        '--image',
        'gcr.io/community-incident-app/community-frontend:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080',
        '--set-env-vars',
        'NODE_ENV=production'
      ]

images:
  - 'gcr.io/community-incident-app/community-backend:$SHORT_SHA'
  - 'gcr.io/community-incident-app/community-frontend:$SHORT_SHA'
