name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Install client dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Run server lint/build/test (optional)
        working-directory: ./server
        run: npm run lint || echo "No lint script"

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker containers (test)
        run: docker compose up -d

      - name: Wait for containers to be ready
        run: sleep 10

      - name: Check if frontend is running
        run: curl -I http://localhost:3000 || exit 1

      - name: Check if backend is running
        run: curl -I http://localhost:5000 || exit 1
